Issue23 mission statement
UofA-Blueprint/uofablueprint.org pull request #10
Opened 2022-06-16 21:15 UTC by GurveerSohal

2022-06-21 02:30 UTC, dimassudjito requested changes

2022-06-21 02:30 UTC, dimassudjito commented on frontend/src/components/about/Mission.js
> +            </Typography>
Decrease the size to match mockup. Also, is it possible to get it more bolded?

2022-06-21 02:30 UTC, dimassudjito commented on frontend/src/components/about/Mission.js
> +            </Typography>
Can use <br/> to create a manual break in the text. Or can you use Box to limit the width of the statement

2022-06-21 18:31 UTC, GurveerSohal commented on frontend/src/components/about/Mission.js
> +            </Typography>
made changes

2022-06-22 02:31 UTC, dimassudjito requested changes

2022-06-22 02:31 UTC, dimassudjito commented on frontend/src/components/about/Mission.js
> +                communities and promote public welfare.
color should be dark gray instead of black

2022-06-22 02:31 UTC, dimassudjito commented on frontend/src/components/about/Mission.js
> +            </Typography>
maybe it can be h4/h5 instead

2022-06-23 16:52 UTC, GurveerSohal commented on frontend/src/components/about/Mission.js
> +            </Typography>
made changes

2022-06-26 22:12 UTC, dimassudjito approved these changes

2022-06-26 22:12 UTC, merged