Issue54consolidate components
UofA-Blueprint/uofablueprint.org pull request #27
Opened 2022-06-30 14:29 UTC by GurveerSohal

2022-07-05 17:49 UTC, filippociandy10 approved these changes

2022-07-06 02:20 UTC, dimassudjito commented
Checklist for code reviewers

General Check

- [ ]  Check that the code compiles and runs
- [ ]  Check that the code is producing the required output by comparing it to the acceptance criteria in the GitHub issues. (e.g., compare it with Figma sketch for frontend work)
- [ ]  Check that the code has acceptable tests and that the tests are passing.
- [ ]  Check that the PR is directed at the correct branch (develop Vs. main)
- [ ]  Check that the PR does not have merge conflict
- [ ]  Check that CI/CD tests are passing (failure is resolved in latest develop branch)

Implementation Review

- [ ]  Understand implementation approach and give feedback on how we can improve the general approach
- [ ]  Understand data structures being used in the implementation and provide feedback (i.e., is it optimal?)
- [ ]  Understand external libraries used in the implementation and provide feedback (i.e., is it deprecated? Is there better libraries out there?)
- [ ]  Check for repeated code and give feedback
- [ ]  Check for performance-intensive code (e.g., heavy algorithm) and give feedback
- [ ]  Check for dead code or commented code that should be deleted
- [ ]  Check if variable names are sensible and descriptive

2022-07-06 02:28 UTC, dimassudjito requested changes
Looking almost ready, a couple things:

- add top and bottom margin from the "Meet the team" subtitle
- add more bottom margin from the team section (so it has more space from the footer)
- fix tests (can remove un-used tests) as ci/cd needs all tests to pass

2022-07-06 02:28 UTC, dimassudjito commented on frontend/src/pages/About.js
> +                    buttonText='Learn more'
button should scroll to the adjacent section when click, we can maybe pass the href value for the button as a prop but this is not the only way to do the scrolling effect

2022-07-06 02:28 UTC, dimassudjito commented on frontend/src/components/about/Value.js
>  import React from 'react'
awesome refactoring nice

2022-07-06 02:28 UTC, dimassudjito commented on frontend/src/components/about/Value.js
> +            }}> Our Values </Typography>
we should add more bottom margin from the "Our Values" subtitle to the list of values

2022-07-15 00:06 UTC, dimassudjito approved these changes

2022-07-15 00:16 UTC, merged