Service
UofA-Blueprint/uofablueprint.org pull request #28
Opened 2022-07-02 04:29 UTC by Aaron383

Created service component

2022-07-05 01:42 UTC, GurveerSohal requested changes
Add a test to see if the component appears on the screen. Also you can format it to be a bit cleaner if you want (remove the extra spaces, and indent the nested boxes).

2022-07-05 01:42 UTC, GurveerSohal commented on frontend/src/components/nonprofitApply/Service.js
> +
Remove unnecessary spacing

2022-07-05 01:42 UTC, GurveerSohal commented on frontend/src/components/nonprofitApply/Service.js
> +                    This might be better for applications that need to be publicly available or ones that help facilitate task management.</Typography>
Create a break in the paragraph to match the figma sketch. Can be done by fixing the width of the box or using a break statement.

2022-07-16 00:12 UTC, dimassudjito approved these changes
I wanted to suggest a couple changes (e.g., change "Our Service" to dark blue) but I think we can handle that in another ticket since we need to add App Development to this component as well

2022-07-16 00:12 UTC, merged