Feature/issue number37 team component
UofA-Blueprint/uofablueprint.org pull request #7
Opened 2022-06-10 03:09 UTC by GurveerSohal

2022-06-15 01:24 UTC, dimassudjito requested changes
Really good job on the MUI refactoring. Some visual formatting changes and we'll be ready to merge

2022-06-15 01:24 UTC, dimassudjito commented on frontend/src/components/about/Member.js
> +// }
delete

2022-06-15 01:24 UTC, dimassudjito commented on frontend/src/components/about/Member.js
> +            </Typography>
add more bottom margin

2022-06-15 01:24 UTC, dimassudjito commented on frontend/src/components/about/MemberInfo.js
> +                    title = {name}
can we decrease the font size of this

2022-06-15 01:24 UTC, dimassudjito commented on frontend/src/components/about/MemberInfo.js
> +                    subheader = {position}
can we center-aligned this instead of left-aligned

2022-06-15 01:24 UTC, dimassudjito commented on frontend/src/components/about/Member.js
> +    const LINK_IMAGE = "https://cdn-icons-png.flaticon.com/512/38/38669.png";
do we still need this now that we use icon from mui

2022-06-15 01:24 UTC, dimassudjito commented on frontend/src/components/about/Member.js
> +                        <MemberInfo image={IMG_URI} linkImage={LINK_IMAGE} link={member.linkedin} name={member.name} position={member.position}/>
don't need linkImage prop no more

2022-06-15 18:01 UTC, GurveerSohal commented on frontend/src/components/about/Member.js
> +    const LINK_IMAGE = "https://cdn-icons-png.flaticon.com/512/38/38669.png";
IMG_URI is still needed for the image in the avatar, but I removed the link_image

2022-06-16 02:25 UTC, dimassudjito approved these changes

2022-06-16 02:26 UTC, merged